### ISSUE TITLE
SUPER zoom in rgb show image

### ISSUE THREAD

**Issue by joaosalvado10** [ashwin/kinectv2_viewer#1]
when i run this project the rgb image  appears to be zoomed , any idea why? and how to transform it to the original image?
ty
joao

**Comment by joaosalvado10** [comment]
i have been around it, and i dont konw why the image is zoomed

**Comment by joaosalvado10** [comment]
i solved the problem by doing this:

cv::Mat resizeMat;
		const double scale = 0.5;
		cv::resize(color_mat, resizeMat, cv::Size(), scale, scale);

**Comment by ashwin** [comment]
@joaosalvado10 I'm glad you found the solution :smile:
